"""initial ledger schema

Revision ID: e9587aa1cc01
Revises: 
Create Date: 2026-09-07 11:37:45.384685
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e9587aa1cc01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_event',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=32), nullable=False),
    sa.Column('from_state', sa.String(length=40), nullable=True),
    sa.Column('to_state', sa.String(length=40), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('ledger_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_event_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_event_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_event_ts'), ['ts'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role in ('reviewer', 'operator')", name='ck_api_key_role'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_key_project_id'), ['project_id'], unique=False)

    op.create_table('model_version',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('ifc_sha256', sa.String(length=64), nullable=False),
    sa.Column('ifc_path', sa.Text(), nullable=False),
    sa.Column('speckle_stream', sa.String(length=120), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aliases_path', sa.Text(), nullable=True),
    sa.Column('programme_path', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['model_version.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_version_ifc_sha256'), ['ifc_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_version_project_id'), ['project_id'], unique=False)

    op.create_table('zone',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=False),
    sa.Column('zone_key', sa.String(length=120), nullable=False),
    sa.Column('level', sa.String(length=120), nullable=False),
    sa.Column('grid_cell', sa.String(length=120), nullable=False),
    sa.Column('buffer_m', sa.Float(), nullable=False),
    sa.Column('congestion', sa.Float(), nullable=False),
    sa.Column('programme_rank', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('element_count', sa.Integer(), nullable=False),
    sa.Column('element_gids', sa.JSON(), nullable=False),
    sa.Column('dedicated_reason', sa.String(length=60), nullable=True),
    sa.Column('branch', sa.String(length=160), nullable=True),
    sa.CheckConstraint("status in ('queued', 'active', 'awaiting_review', 'merged')", name='ck_zone_status'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'zone_key', name='uq_zone_key_per_version')
    )
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zone_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_zone_status'), ['status'], unique=False)

    op.create_table('clash',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model_version_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=True),
    sa.Column('clash_key', sa.String(length=200), nullable=False),
    sa.Column('a_gid', sa.String(length=64), nullable=False),
    sa.Column('b_gid', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('depth_or_gap_mm', sa.Float(), nullable=True),
    sa.Column('systems', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('rule_id', sa.String(length=80), nullable=True),
    sa.Column('required_gap_mm', sa.Float(), nullable=True),
    sa.Column('severity_mm', sa.Float(), nullable=False),
    sa.Column('resolution_rank', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("owner in ('zone', 'coordinator')", name='ck_clash_owner'),
    sa.CheckConstraint("state in ('open', 'proposed', 'verified', 'approved', 'merged', 'resolved', 'regressed', 'escalated')", name='ck_clash_state'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_version_id', 'clash_key', name='uq_clash_key_per_version')
    )
    with op.batch_alter_table('clash', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clash_clash_key'), ['clash_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_clash_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clash_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_clash_zone_id'), ['zone_id'], unique=False)
        batch_op.create_index('ix_clash_zone_state', ['zone_id', 'state'], unique=False)

    op.create_table('review_decision',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.String(length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('change_set_ref', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision in ('approve', 'reject', 'edit')", name='ck_review_decision'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_decision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_decision_zone_id'), ['zone_id'], unique=False)

    op.create_table('proposal',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('clash_id', sa.String(length=32), nullable=False),
    sa.Column('element_gid', sa.String(length=64), nullable=False),
    sa.Column('move_type', sa.String(length=40), nullable=False),
    sa.Column('move_vector', sa.JSON(), nullable=False),
    sa.Column('rule_ids', sa.JSON(), nullable=False),
    sa.Column('clause_text', sa.Text(), nullable=True),
    sa.Column('monitor_geometry', sa.JSON(), nullable=True),
    sa.Column('monitor_boundary', sa.JSON(), nullable=True),
    sa.Column('monitor_integrity', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('superseded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("verdict in ('pending', 'verified', 'rejected', 'flagged_unsourced', 'escalated', 'approved', 'superseded')", name='ck_proposal_verdict'),
    sa.ForeignKeyConstraint(['clash_id'], ['clash.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_clash_id'), ['clash_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_verdict'), ['verdict'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_verdict'))
        batch_op.drop_index(batch_op.f('ix_proposal_clash_id'))

    op.drop_table('proposal')
    with op.batch_alter_table('review_decision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_decision_zone_id'))

    op.drop_table('review_decision')
    with op.batch_alter_table('clash', schema=None) as batch_op:
        batch_op.drop_index('ix_clash_zone_state')
        batch_op.drop_index(batch_op.f('ix_clash_zone_id'))
        batch_op.drop_index(batch_op.f('ix_clash_state'))
        batch_op.drop_index(batch_op.f('ix_clash_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_clash_clash_key'))

    op.drop_table('clash')
    with op.batch_alter_table('zone', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zone_status'))
        batch_op.drop_index(batch_op.f('ix_zone_priority'))
        batch_op.drop_index(batch_op.f('ix_zone_model_version_id'))

    op.drop_table('zone')
    with op.batch_alter_table('model_version', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_version_project_id'))
        batch_op.drop_index(batch_op.f('ix_model_version_ifc_sha256'))

    op.drop_table('model_version')
    with op.batch_alter_table('api_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_key_project_id'))

    op.drop_table('api_key')
    op.drop_table('project')
    with op.batch_alter_table('ledger_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_event_ts'))
        batch_op.drop_index(batch_op.f('ix_ledger_event_entity_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_event_entity'))

    op.drop_table('ledger_event')
    # ### end Alembic commands ###
